mac_task:
  matrix:
    - name: 🍎 Clang
      osx_instance:
        image: mojave-xcode

  install_script:
    - which ruby
    - ruby --version
    - which gem
    - gem --version
    - sudo gem install ronn

  tests_script:
    - true
